spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de logging para mensagens customizadas
logging.level.com.turmaa.helpdesk=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# Personalização da saída do console
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

# Banner personalizado ativado
spring.banner.location=classpath:banner.txt

# Informações da aplicação
spring.application.name=Helpdesk Turma A
info.app.name=Sistema Helpdesk
info.app.description=Sistema de atendimento e suporte técnico
info.app.version=1.0.0

# Configurações JWT
jwt.secret=StringUsadaParaGerarToken
jwt.expiration=604800000
